Repository Signo23/OOP21-aren-adv, pull requests merged in 2022-04, with the labels that each got.

#26 Engine graphic
  src/main/java/it/aren/App.java
  src/main/java/it/aren/common/Constant.java
  src/main/java/it/aren/core/GameEngine.java
  src/main/java/it/aren/graphic/SwingPanel.java
  src/main/java/it/aren/graphic/SwingView.java
Labels: new, upgrade

#27 12 factory
  src/main/java/it/aren/core/GameFactory.java
  src/main/java/it/aren/input/InputComponent.java
  src/main/java/it/aren/input/PlayerInputComponent.java
  src/main/java/it/aren/model/GameState.java
  src/main/java/it/aren/model/World.java
Labels: bug, new

#30 Fix InputComponent Error
  bin/.gitignore
  src/main/java/it/aren/input/InputComponent.java
  src/main/java/it/aren/input/PlayerInputComponent.java
Labels: bug

#32 28 implements factory in game
  src/main/java/it/aren/core/GameEngine.java
  src/main/java/it/aren/graphic/SwingPanel.java
  src/main/java/it/aren/graphic/SwingView.java
Labels: upgrade

#34 Add idle field in Player
  src/main/java/it/aren/model/Player.java
Labels: upgrade

#35 31 world
  src/main/java/it/aren/model/GameState.java
  src/main/java/it/aren/model/World.java
Labels: upgrade

#37 Add idle control
  src/main/java/it/aren/input/PlayerInputComponent.java
Labels: upgrade

#38 Base physics
  src/main/java/it/aren/common/Constant.java
  src/main/java/it/aren/physics/PhysicsComponent.java
  src/main/java/it/aren/physics/PlayerPhysicsComponenent.java
Labels: new

#40 Add KeyListenerImpl class
  src/main/java/it/aren/graphic/KeyListenerImpl.java
Labels: new

#42 Implement physic in entities
  src/main/java/it/aren/core/GameEngine.java
  src/main/java/it/aren/graphic/SwingPanel.java
  src/main/java/it/aren/graphic/SwingView.java
  src/main/java/it/aren/model/Player.java
Labels: upgrade

#45 Update player constructor
  src/main/java/it/aren/core/GameFactory.java
Labels: upgrade

#47 46 change key code in keylistenerimpl
  src/main/java/it/aren/common/Constant.java
  src/main/java/it/aren/graphic/KeyListenerImpl.java
Labels: upgrade

#49 Fix direction coordinates
  src/main/java/it/aren/common/Constant.java
  src/main/java/it/aren/input/PlayerInputComponent.java
Labels: bug

#51 Add KeyEvent constant
  src/main/java/it/aren/common/Constant.java
  src/main/java/it/aren/graphic/KeyListenerImpl.java
Labels: upgrade

#54 Move KeyListenerImpl to package input
  src/main/java/it/aren/graphic/KeyListenerImpl.java
  src/main/java/it/aren/graphic/SwingPanel.java
  src/main/java/it/aren/input/KeyListenerImpl.java
Labels: upgrade

#59 Javadoc
  .classpath
  .settings/org.eclipse.buildship.core.prefs
  src/main/java/it/aren/App.java
  src/main/java/it/aren/common/Constant.java
  src/main/java/it/aren/common/Point2D.java
  src/main/java/it/aren/core/GameEngine.java
  src/main/java/it/aren/graphic/BlockGraphicComponent.java
  src/main/java/it/aren/graphic/GraphicComponent.java
  src/main/java/it/aren/graphic/GraphicController.java
  src/main/java/it/aren/graphic/PlayerGraphicComponent.java
  src/main/java/it/aren/graphic/SwingGraphic.java
  src/main/java/it/aren/graphic/SwingPanel.java
  src/main/java/it/aren/graphic/SwingView.java
  src/main/java/it/aren/graphic/View.java
  src/main/java/it/aren/model/Block.java
  src/main/java/it/aren/model/Entity.java
  src/main/java/it/aren/model/GameMap.java
  src/main/java/it/aren/model/GameObject.java
  src/main/java/it/aren/model/Player.java
Labels: documentation

#60 Add JavaDoc
  src/main/java/it/aren/core/GameFactory.java
  src/main/java/it/aren/input/InputComponent.java
  src/main/java/it/aren/input/InputController.java
  src/main/java/it/aren/input/KeyListenerImpl.java
  src/main/java/it/aren/input/KeyboardInputController.java
  src/main/java/it/aren/input/PlayerInputComponent.java
  src/main/java/it/aren/model/GameState.java
  src/main/java/it/aren/model/World.java
Labels: documentation

#61 Add JavaDoc
  src/main/java/it/aren/physics/PhysicsComponent.java
  src/main/java/it/aren/physics/PlayerPhysicsComponent.java
Labels: documentation

#62 Ver 0.1.0
  .checkstyle
  .classpath
  .eclipse-pmd
  .gitattributes
  .gitignore
  .project
  .settings/edu.umd.cs.findbugs.core.prefs
  .settings/org.eclipse.buildship.core.prefs
  .settings/org.eclipse.core.resources.prefs
  .settings/org.eclipse.core.runtime.prefs
  .settings/org.eclipse.jdt.core.prefs
  .settings/org.eclipse.jdt.ui.prefs
  README.md
  build.gradle.kts
  config/checkstyle/checkstyle.xml
  config/checkstyle/suppressions.xml
  config/eclipse-code-style.xml
  config/pmd/pmd.xml
  config/spotbugs/excludes.xml
  gradlew
  gradlew.bat
  settings.gradle.kts
  src/main/java/it/aren/App.java
  src/main/java/it/aren/common/Constant.java
  src/main/java/it/aren/common/Point2D.java
  src/main/java/it/aren/core/GameEngine.java
  src/main/java/it/aren/core/GameFactory.java
  src/main/java/it/aren/event/Event.java
  src/main/java/it/aren/event/NullEvent.java
  src/main/java/it/aren/graphic/BlockGraphicComponent.java
  src/main/java/it/aren/graphic/GraphicComponent.java
  src/main/java/it/aren/graphic/GraphicController.java
  src/main/java/it/aren/graphic/PlayerGraphicComponent.java
  src/main/java/it/aren/graphic/SwingGraphic.java
  src/main/java/it/aren/graphic/SwingPanel.java
  src/main/java/it/aren/graphic/SwingView.java
  src/main/java/it/aren/graphic/View.java
  src/main/java/it/aren/input/InputComponent.java
  src/main/java/it/aren/input/InputController.java
  src/main/java/it/aren/input/KeyListenerImpl.java
  src/main/java/it/aren/input/KeyboardInputController.java
  src/main/java/it/aren/input/PlayerInputComponent.java
  src/main/java/it/aren/model/Block.java
  src/main/java/it/aren/model/Entity.java
  src/main/java/it/aren/model/GameMap.java
  src/main/java/it/aren/model/GameObject.java
  src/main/java/it/aren/model/GameState.java
  src/main/java/it/aren/model/Player.java
  src/main/java/it/aren/model/World.java
  src/main/java/it/aren/physics/PhysicsComponent.java
  src/main/java/it/aren/physics/PlayerPhysicsComponent.java
Labels: new

#64 Texture
  .settings/edu.umd.cs.findbugs.core.prefs
  .settings/org.eclipse.jdt.core.prefs
  .settings/org.eclipse.jdt.ui.prefs
  src/main/java/it/aren/common/Constant.java
  src/main/java/it/aren/graphic/GameMapGraphicComponent.java
  src/main/java/it/aren/graphic/GraphicController.java
  src/main/java/it/aren/graphic/SwingGraphic.java
  src/main/java/it/aren/graphic/SwingPanel.java
  src/main/java/it/aren/graphic/SwingView.java
  src/main/java/it/aren/graphic/Texture.java
  src/main/java/it/aren/model/Block.java
  src/main/java/it/aren/model/GameMap.java
  src/main/resources/assets/textures/chest.png
  src/main/resources/assets/textures/level-one.png
  src/main/resources/assets/textures/player.png
Labels: upgrade

#65 Write comments for JavaDoc's generation
  src/main/java/it/aren/common/Constant.java
  src/main/java/it/aren/graphic/BlockGraphicComponent.java
  src/main/java/it/aren/graphic/GameMapGraphicComponent.java
  src/main/java/it/aren/graphic/GraphicController.java
  src/main/java/it/aren/graphic/PlayerGraphicComponent.java
  src/main/java/it/aren/graphic/Texture.java
  src/main/java/it/aren/model/GameMap.java
Labels: documentation

#67 Event
  src/main/java/it/aren/core/GameEngine.java
  src/main/java/it/aren/event/Event.java
  src/main/java/it/aren/event/EventListener.java
  src/main/java/it/aren/event/GiveToPlayerEvent.java
  src/main/java/it/aren/event/NullEvent.java
  src/test/java/it/aren/event/Events.java
Labels: new

#70 Update Event for manage requirement
  src/main/java/it/aren/event/GiveToPlayerEvent.java
  src/main/java/it/aren/event/InteractWithPlayerEvent.java
  src/test/java/it/aren/event/Events.java
Labels: upgrade
