Repository Signo23/OOP21-aren-adv, pull requests merged in 2022-06, with the labels that each got.

#96 Upgrade entities
  src/main/java/it/aren/common/Constant.java
  src/main/java/it/aren/common/ObjectType.java
  src/main/java/it/aren/core/GameFactory.java
  src/main/java/it/aren/graphic/BlockGraphicComponent.java
  src/main/java/it/aren/graphic/DialogGraphicComponent.java
  src/main/java/it/aren/graphic/GameMapGraphicComponent.java
  src/main/java/it/aren/graphic/GameObjectGraphicComponent.java
  src/main/java/it/aren/graphic/GraphicComponent.java
  src/main/java/it/aren/graphic/PlayerGraphicComponent.java
  src/main/java/it/aren/graphic/SwingGraphic.java
  src/main/java/it/aren/graphic/SwingPanel.java
  src/main/java/it/aren/input/DialogInputComponent.java
  src/main/java/it/aren/input/InputComponent.java
  src/main/java/it/aren/input/PlayerInputComponent.java
  src/main/java/it/aren/model/BaseEntity.java
  src/main/java/it/aren/model/Block.java
  src/main/java/it/aren/model/Dialog.java
  src/main/java/it/aren/model/GameMap.java
  src/main/java/it/aren/model/GameObject.java
  src/main/java/it/aren/model/GameState.java
  src/main/java/it/aren/model/Player.java
  src/main/java/it/aren/physics/PhysicsComponent.java
  src/main/java/it/aren/physics/PlayerPhysicsComponent.java
Labels: upgrade

#98 97 dialog
  src/main/java/it/aren/common/Constant.java
  src/main/java/it/aren/core/GameEngine.java
  src/main/java/it/aren/core/GameFactory.java
  src/main/java/it/aren/graphic/SwingGraphic.java
  src/main/java/it/aren/input/DialogInputComponent.java
  src/main/java/it/aren/model/Dialog.java
  src/main/java/it/aren/model/World.java
Labels: upgrade

#104 Implemented Settings
  src/main/java/it/aren/common/ObjectType.java
  src/main/java/it/aren/core/GameEngine.java
  src/main/java/it/aren/core/GameFactory.java
  src/main/java/it/aren/graphic/Animation.java
  src/main/java/it/aren/graphic/SwingGraphic.java
  src/main/java/it/aren/graphic/SwingView.java
  src/main/java/it/aren/graphic/Texture.java
Labels: upgrade

#106 105 add more game map
  src/main/java/it/aren/common/BaseLevelEnum.java
  src/main/java/it/aren/common/PointRange.java
  src/main/java/it/aren/core/GameFactory.java
  src/main/java/it/aren/event/TransportEvent.java
  src/main/java/it/aren/file/MapsLoader.java
  src/main/java/it/aren/graphic/SwingGraphic.java
  src/main/java/it/aren/model/Dialog.java
  src/main/java/it/aren/model/GameMap.java
  src/main/java/it/aren/model/GameState.java
  src/main/java/it/aren/model/World.java
  src/main/resources/maps.json
Labels: new

#107 Ver 0.4.0
  config/checkstyle/checkstyle.xml
  src/main/java/it/aren/common/BaseLevelEnum.java
  src/main/java/it/aren/common/BaseObjectEnum.java
  src/main/java/it/aren/common/Constant.java
  src/main/java/it/aren/common/ObjectType.java
  src/main/java/it/aren/common/PointRange.java
  src/main/java/it/aren/common/Settings.java
  src/main/java/it/aren/core/GameEngine.java
  src/main/java/it/aren/core/GameFactory.java
  src/main/java/it/aren/event/TransportEvent.java
  src/main/java/it/aren/file/FileSaver.java
  src/main/java/it/aren/file/ImageLoader.java
  src/main/java/it/aren/file/MapsLoader.java
  src/main/java/it/aren/file/SettingsLoader.java
  src/main/java/it/aren/file/SettingsSaver.java
  src/main/java/it/aren/graphic/PlayerAnimation.java
  src/main/java/it/aren/graphic/PlayerGraphicComponent.java
  src/main/java/it/aren/graphic/SwingGraphic.java
  src/main/java/it/aren/graphic/SwingPanel.java
  src/main/java/it/aren/graphic/SwingView.java
  src/main/java/it/aren/graphic/Texture.java
  src/main/java/it/aren/model/BaseEntity.java
  src/main/java/it/aren/model/Block.java
  src/main/java/it/aren/model/Dialog.java
  src/main/java/it/aren/model/GameMap.java
  src/main/java/it/aren/model/GameObject.java
  src/main/java/it/aren/model/GameState.java
  src/main/java/it/aren/model/Player.java
  src/main/java/it/aren/model/World.java
  src/main/java/it/aren/physics/PlayerPhysicsComponent.java
  src/main/resources/maps.json
  src/test/java/it/aren/physics/CollisionTest.java
Labels: new

#110 Main Menu
  src/main/java/it/aren/common/BaseActionEnum.java
  src/main/java/it/aren/common/BaseObjectEnum.java
  src/main/java/it/aren/core/GameEngine.java
  src/main/java/it/aren/graphic/SwingView.java
  src/main/java/it/aren/graphic/View.java
  src/main/java/it/aren/graphic/menu/MenuButton.java
  src/main/java/it/aren/graphic/menu/MenuPanel.java
  src/main/java/it/aren/input/BaseMenuInputController.java
  src/main/java/it/aren/input/MenuInputController.java
Labels: new

#113 Ver 0.5.0
  src/main/java/it/aren/App.java
  src/main/java/it/aren/common/ApplicationState.java
  src/main/java/it/aren/common/BaseActionEnum.java
  src/main/java/it/aren/common/BaseLevelEnum.java
  src/main/java/it/aren/common/BaseObjectEnum.java
  src/main/java/it/aren/core/GameEngine.java
  src/main/java/it/aren/graphic/SwingView.java
  src/main/java/it/aren/graphic/View.java
  src/main/java/it/aren/graphic/menu/MenuButton.java
  src/main/java/it/aren/graphic/menu/MenuCheckBox.java
  src/main/java/it/aren/graphic/menu/MenuCombo.java
  src/main/java/it/aren/graphic/menu/MenuPanel.java
  src/main/java/it/aren/graphic/menu/MenuSettingsPanel.java
  src/main/java/it/aren/graphic/menu/ReadableDimension.java
  src/main/java/it/aren/input/BaseMenuInputController.java
  src/main/java/it/aren/input/MenuInputController.java
  src/main/resources/assets/textures/banner.png
  src/main/resources/assets/textures/check-off.png
  src/main/resources/assets/textures/check-on.png
  src/main/resources/assets/textures/clear.png
  src/main/resources/assets/textures/level-four.png
  src/main/resources/assets/textures/level-one.png
  src/main/resources/assets/textures/level-three.png
  src/main/resources/assets/textures/level-two.png
  src/main/resources/assets/textures/save.png
Labels: upgrade

#115 Fix Events with no interaction
  src/main/java/it/aren/event/NullEvent.java
  src/main/java/it/aren/event/TransportEvent.java
Labels: bug

#118 Change icon of app
  src/main/java/it/aren/common/BaseObjectEnum.java
  src/main/java/it/aren/graphic/SwingView.java
Labels: upgrade

#120 Refactor graphics package
  src/main/java/it/aren/core/GameEngine.java
  src/main/java/it/aren/core/GameFactory.java
  src/main/java/it/aren/graphic/AppView.java
  src/main/java/it/aren/graphic/BaseView.java
  src/main/java/it/aren/graphic/GameObjectGraphicComponent.java
  src/main/java/it/aren/graphic/GraphicComponent.java
  src/main/java/it/aren/graphic/GraphicController.java
  src/main/java/it/aren/graphic/component/BlockGraphicComponent.java
  src/main/java/it/aren/graphic/component/DialogGraphicComponent.java
  src/main/java/it/aren/graphic/component/GameMapGraphicComponent.java
  src/main/java/it/aren/graphic/component/GameObjectGraphicComponent.java
  src/main/java/it/aren/graphic/component/PlayerGraphicComponent.java
  src/main/java/it/aren/graphic/game/GameGraphicController.java
  src/main/java/it/aren/graphic/game/GamePanel.java
  src/main/java/it/aren/graphic/game/PlayerAnimation.java
  src/main/java/it/aren/model/GameMap.java
  src/test/java/it/aren/event/Events.java
Labels: documentation, upgrade

#126 Add a start message
  src/main/java/it/aren/core/GameEngine.java
  src/main/java/it/aren/event/InteractWithPlayerEvent.java
Labels: new, upgrade

#128 Refactor models package
  src/main/java/it/aren/core/GameEngine.java
  src/main/java/it/aren/core/GameFactory.java
  src/main/java/it/aren/event/InteractWithPlayerEvent.java
  src/main/java/it/aren/graphic/GraphicController.java
  src/main/java/it/aren/graphic/component/BlockGraphicComponent.java
  src/main/java/it/aren/graphic/component/DialogGraphicComponent.java
  src/main/java/it/aren/graphic/component/GameMapGraphicComponent.java
  src/main/java/it/aren/graphic/component/GameObjectGraphicComponent.java
  src/main/java/it/aren/graphic/component/PlayerGraphicComponent.java
  src/main/java/it/aren/graphic/game/GameGraphicController.java
  src/main/java/it/aren/graphic/game/PlayerAnimation.java
  src/main/java/it/aren/input/PlayerInputComponent.java
  src/main/java/it/aren/model/BaseEntity.java
  src/main/java/it/aren/model/Block.java
  src/main/java/it/aren/model/GameObject.java
  src/main/java/it/aren/model/GameState.java
  src/main/java/it/aren/model/World.java
  src/main/java/it/aren/model/game/Block.java
  src/main/java/it/aren/model/game/Dialog.java
  src/main/java/it/aren/model/game/GameMap.java
  src/main/java/it/aren/model/game/GameObject.java
  src/main/java/it/aren/model/game/Player.java
  src/main/java/it/aren/physics/PlayerPhysicsComponent.java
  src/test/java/it/aren/event/Events.java
  src/test/java/it/aren/input/Input.java
  src/test/java/it/aren/physics/CollisionTest.java
Labels: documentation, upgrade

#129 Change transport positions
  src/main/java/it/aren/core/GameFactory.java
Labels: bug

#130 Print multiline dialog
  src/main/java/it/aren/graphic/game/GameGraphicController.java
Labels: upgrade

#131 Modify pointRange position
  src/main/resources/maps.json
Labels: bug

#134 Refactor events package
  src/main/java/it/aren/core/GameEngine.java
  src/main/java/it/aren/event/BaseEvent.java
  src/main/java/it/aren/event/EventListener.java
  src/main/java/it/aren/event/InteractWithPlayerEvent.java
  src/main/java/it/aren/event/NullEvent.java
  src/main/java/it/aren/event/TransportEvent.java
  src/main/java/it/aren/model/game/Block.java
  src/test/java/it/aren/event/Events.java
Labels: documentation, upgrade

#136 Settings Menu doesn't load settings
  src/main/java/it/aren/graphic/AppView.java
  src/main/java/it/aren/graphic/menu/MenuSettingsPanel.java
Labels: bug

#137 109 test gamemap change
  src/main/java/it/aren/model/Hud.java
  src/test/java/it/aren/event/TransportEvents.java
  src/test/java/it/aren/input/Input.java
Labels: new

#141 140 add npc
  src/main/java/it/aren/common/BaseLevelEnum.java
  src/main/java/it/aren/core/GameFactory.java
  src/main/java/it/aren/file/MapsLoader.java
  src/main/java/it/aren/input/PlayerInputComponent.java
  src/main/java/it/aren/model/GameState.java
  src/test/java/it/aren/event/TransportEvents.java
  src/test/java/it/aren/input/Input.java
Labels: new

#144 143 fix checkstyle error
  src/main/java/it/aren/common/Point2D.java
  src/main/java/it/aren/common/PointRange.java
  src/main/java/it/aren/common/Settings.java
  src/main/java/it/aren/core/GameFactory.java
  src/main/java/it/aren/graphic/BaseView.java
  src/main/java/it/aren/graphic/menu/MenuCheckBox.java
  src/main/java/it/aren/graphic/menu/MenuCombo.java
  src/main/java/it/aren/graphic/menu/MenuPanel.java
  src/main/java/it/aren/graphic/menu/MenuSettingsPanel.java
  src/main/java/it/aren/input/InputComponent.java
  src/main/java/it/aren/input/InputController.java
  src/main/java/it/aren/input/KeyListenerImpl.java
  src/main/java/it/aren/input/KeyboardInputController.java
  src/main/java/it/aren/input/PlayerInputComponent.java
  src/main/java/it/aren/model/GameState.java
  src/main/java/it/aren/model/game/Dialog.java
  src/test/java/it/aren/event/TransportEvents.java
Labels: bug

#146 Handled SettingsLoader exception
  src/main/java/it/aren/file/SettingsLoader.java
Labels: bug
