Repository Signo23/OOP21-aren-adv, pull requests merged in 2022-03, with the labels that each got.

#2 Create gradle base
  .checkstyle
  .classpath
  .eclipse-pmd
  .gitattributes
  .gitignore
  .project
  .settings/edu.umd.cs.findbugs.core.prefs
  .settings/org.eclipse.buildship.core.prefs
  .settings/org.eclipse.core.resources.prefs
  .settings/org.eclipse.core.runtime.prefs
  .settings/org.eclipse.jdt.core.prefs
  .settings/org.eclipse.jdt.ui.prefs
  bin/.gitignore
  build.gradle.kts
  config/checkstyle/checkstyle.xml
  config/checkstyle/suppressions.xml
  config/eclipse-code-style.xml
  config/pmd/pmd.xml
  config/spotbugs/excludes.xml
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
  src/main/java/it/aren/App.java
Labels: enhancement

#8 Entities
  src/main/java/it/aren/common/Point2D.java
  src/main/java/it/aren/model/Block.java
  src/main/java/it/aren/model/Entity.java
  src/main/java/it/aren/model/GameObject.java
  src/main/java/it/aren/model/Player.java
Labels: enhancement

#9 Gamemap
  src/main/java/it/aren/common/Constant.java
  src/main/java/it/aren/model/GameMap.java
Labels: enhancement

#10 Events
  src/main/java/it/aren/event/Event.java
  src/main/java/it/aren/event/NullEvent.java
  src/main/java/it/aren/model/Block.java
Labels: enhancement

#11 Add InputComponent and InputController
  .classpath
  .project
  .settings/org.eclipse.buildship.core.prefs
  src/main/java/it/aren/input/InputComponent.java
  src/main/java/it/aren/input/InputController.java
  src/main/java/it/aren/input/KeyboardInputController.java
  src/main/java/it/aren/input/PlayerInputComponent.java
Labels: new

#13 Graphics
  src/main/java/it/aren/common/Constant.java
  src/main/java/it/aren/common/Point2D.java
  src/main/java/it/aren/graphic/BlockGraphicComponent.java
  src/main/java/it/aren/graphic/GraphicComponent.java
  src/main/java/it/aren/graphic/GraphicController.java
  src/main/java/it/aren/graphic/PlayerGraphicComponent.java
  src/main/java/it/aren/graphic/SwingGraphic.java
  src/main/java/it/aren/graphic/SwingView.java
  src/main/java/it/aren/graphic/View.java
  src/main/java/it/aren/model/Block.java
  src/main/java/it/aren/model/Entity.java
  src/main/java/it/aren/model/Player.java
Labels: new

#20 Fixed and updated input's and graphic's component uses in Entity
  .gitignore
  src/main/java/it/aren/model/Block.java
  src/main/java/it/aren/model/Entity.java
  src/main/java/it/aren/model/GameObject.java
  src/main/java/it/aren/model/Player.java
Labels: bug, upgrade
